--Indexing for query4_opt
CREATE INDEX L_OCR_KEY ON LINEITEM(L_ORDERKEY, L_COMMITDATE, L_RECEIPTDATE);
CREATE INDEX O_ODOP_KEY ON ORDERS(O_ORDERDATE, O_ORDERPRIORITY);
--Indexing for Query3_opt
CREATE INDEX C_MC_KEY ON CUSTOMER(C_MKTSEGMENT, C_CUSTKEY);
CREATE INDEX O_COOD_KEY ON ORDERS(O_CUSTKEY, O_ORDERKEY, O_ORDERDATE);
CREATE INDEX L_SD_KEY ON LINEITEM(L_ORDERKEY, L_SHIPDATE);
